export const PARENT = 'PARENT'
export const PARENTS = 'PARENTS'
export const ERROR_PARENT = 'ERROR_PARENT'
export const LOADING_PARENT = 'LOADING_PARENT'

export const CHILDREN = 'CHILDREN'
export const CHILDRENS = 'CHILDRENS'
export const ERROR_CHILDREN = 'ERROR_CHILDREN'
export const LOADING_CHILDREN = 'LOADING_CHILDREN'

export const MEDICALRECORD = 'MEDICALRECORD'
export const MEDICALRECORDS = 'MEDICALRECORDS'
export const ERROR_MEDICALRECORD = 'ERROR_MEDICALRECORD'
export const LOADING_MEDICALRECORD = 'LOADING_MEDICALRECORD'

export const TREATMENT = 'TREATMENT'
export const ERROR_TREATMENT = 'ERROR_TREATMENT'
export const LOADING_TREATMENT = 'LOADING_TREATMENT'

