export { default as LandingPage } from './Landing'
export { default as DetailMedicalRecord } from './DetailMedicalRecord'
export { default as DetailChildren } from './DetailChildren'
export { default as Find } from './Find'
export { default as Page404 } from './Page404'